johannesjo/angular-material-css-vars

- projects/material-css-vars/src/lib/_variables.scss
Angular Material recently added `tooltip` to the background palette. This PR adds this variable and prevents a build error with 9.0.0-rc7+
Tested by using `npm link`. 
This should probably be merged into a next or v9 branch and not master. Although I don't think this would cause any issues for developers using it with Angular Material 8, since it's additive. 
Closes #13
> fix: add tooltip to background palette

- projects/material-css-vars/src/lib/_internal-helper.scss
- projects/material-css-vars/src/lib/_public-util.scss
The mat-palette function returns a palette that includes contrast-contrast: null. This fix ensures that if mat-css-set-palette-defaults is called with a mat-palette, it does not error. It also removes the need to exclude contrast in the set-palette-defaults mixin.
Add this code to styles.scss to see the error before, or everything working after this fix:
```
$palette: mat-palette($mat-grey);
@include mat-css-set-palette-defaults($palette);
```
alternatively, I could change this to exclude `contrast-contrast` in `set-palette-defaults` like how `contrast` is already excluded. That seems pretty specific to my use-case though.
It would also be fair if you said `set-palette-defaults` should only be called with simple palettes (`$mat-grey` before it is passed in to `mat-palette`). We have a …
> fix: handle non-colors in hex-to-rgb

- projects/material-css-vars/src/lib/_mat-lib-overwrites.scss
As I say in the comment:
> The material mixin passes an opacity to mat-color and also adds opacity to the element if the background-color is not of type 'color'.
This would cause the opacity to get applied twice, resulting in a ripple that is almost invisible.
Instead, we will trust that mat-color handles opacity correctly.
You can see the difference when you click on any colored button in the demo app. In the current version, ripples are not visible. This fixes that.
> fix: button ripples shouldn't get opacity applied twice

- projects/material-css-vars/src/lib/material-css-vars.service.ts
The use of the global window object in the service prevents the use of angular universal. Would be great you could merge!
Thanks for your work!
> Use injected document in service instead of global object

- README.md
- projects/material-css-vars/src/lib/_main.scss
- src/app/_app.theme.scss
- src/app/app.component.html
- src/styles.scss
This may not be necessary for anyone using variables directly or the convenience mixins provided by this library, but it will be helpful for anyone who is still using traditional scss mixins to do theming in their app. It is also the best way for an app theme to access $is-dark or items in the background/foreground palettes.
Closes #26
> feat: allow app theme mixins

- projects/material-css-vars/src/lib/_mat-lib-overwrites.scss
- src/app/app.component.html
I'm not sure why the alpha of the ```hint-text: var(--palette-foreground-hint-text),``` is 1.
It is correctly going to alpha 0.5 white in dark mode.
But it is alpha 1 in light mode when it should be 0.38.
Dark mode will still override this alpha so it doesn't effect dark mode.
If anyone can help me understand the design of foreground and how we are expected to switch between light and dark mode, we can implement this better.
> Added override to show disabled items as faded in light mode.

- projects/material-css-vars/src/lib/_main.scss
- src/styles.scss
This adds the ability to pass a custom $typography-config, but note like #45 to let those scss variables be changed / used by css vars.
Also how to install the packages correctly? with npm it couldn't find the `@ctrl/tinycolor` because its only in the projects/-folder
> enable passing $typography-config to mat-core

- projects/material-css-vars/src/lib/material-css-vars.service.ts
This PR changes the way css variables are written to the document element by using angulars `Renderer2`. The reason is that direct DOM changes on the elements are not working when using server side rendering.
Resolves #56
> Add Renderer2 for DOM style manipulation

- README.md
- projects/material-css-vars/package.json
- projects/material-css-vars/src/lib/_main.scss
* Fixes a Sass build error related to missing package exports. Updated paths of scss files:
* `_main.scss` can now be imported via `@import "angular-material-css-vars"` or `@import "angular-material-css-vars/main"`
* `_public-util.scss` can now be imported via `@import "angular-material-css-vars/public-utils"`
* `_variables.scss` can now be imported via `@import "angular-material-css-vars/variables"`
* Add support for loading styles of Angular Material Legacy Components
#103
> Fixes follow-up issues with Angular 15

- projects/material-css-vars/src/lib/_main.scss
Fixes the `mat-typography` CSS class, previously it was not correctly applying the typography config
Closes #111
> Fix typography

- projects/material-css-vars/package.json
Exposes `src/lib` paths in `package.json`, because apparently ng-packagr doesn't fully support `exports` and only works if under the given path there is actually a SCSS file.
Closes #94
> fix: expose src/lib paths for projects using ng-packagr

- projects/material-css-vars/src/lib/_public-util.scss
Opacity was not being respected on the `_public-util.scss` `mat-css-color` utils after a certain commit. This PR restores that functionality.
Fixes: https://github.com/johannesjo/angular-material-css-vars/issues/121
> Respect opacity in color utils

- projects/material-css-vars/src/lib/_public-util.scss
When `$dark-theme-selector` is set to `false`, now all dark theme related styles will be skipped.
Closes #136
> fix: skip all dark theme styles when dark theme selector is set to false

- .eslintrc.json
- package-lock.json
- package.json
- projects/material-css-vars/src/lib/material-css-vars.service.spec.ts
- projects/material-css-vars/src/lib/material-css-vars.service.ts
- projects/material-css-vars/src/test/integration.spec.ts
- src/app/app.component.ts
- src/app/app.module.ts
- src/main.ts
* Update all dependencies to their latest versions
* Enable more strict lint rules for TypeScript files, like suggested in the TypeScript ESLint v6 migration guide
> chore: update dependencies & lint rules

- projects/material-css-vars/src/lib/_mat-lib-overwrites.scss
Ensures that the checkbox check mark color is the contrast color of the used checkbox background color
Closes #147
> fix: ensure correct checkbox check mark color

- .github/FUNDING.yml
- projects/material-css-vars/src/lib/material-css-vars.service.spec.ts
- projects/material-css-vars/src/lib/material-css-vars.service.ts
- projects/material-css-vars/src/test/integration.spec.ts
Updates the auto contrast functionality by calculating the actual contrast agains black and white, and choosing the color with the better contrast.
Partly fixes #143
> fix: choose auto contrast color based on calculated contrast

- projects/material-css-vars/package.json
- projects/material-css-vars/src/lib/legacy/main.scss
- projects/material-css-vars/src/lib/legacy/public-color-util.scss
- projects/material-css-vars/src/lib/legacy/public-util.scss
- projects/material-css-vars/src/lib/legacy/variables.scss
Deprecates the `src/lib/*` SCSS entrypoints. With the new single entrypoint it should not be necessary anymore to use them in any case.
n/a
> refactor: deprecate src/lib/* SCSS entrypoints

- projects/material-css-vars/src/lib/_variables.scss
- projects/material-css-vars/src/lib/material-css-vars.service.ts
- projects/material-css-vars/src/test/integration.spec.ts
Changes the contrast text color on light backgrounds from `rgba(0, 0, 0, 0.87)` to `#000000`. This improves the contrast. There are colors where both `#ffffff` and `rgba(0, 0, 0, 0.87)` do not have a sufficient contrast of minimum 4.5, i.e. `#f0002f`.
#143
> fix: maximize contrast of dark texts on light backgrounds

- projects/material-css-vars/src/lib/material-css-vars.service.ts
Breaking Change:
`MaterialCssVarsService`'s attribute `isDarkTheme` now can be undefined
> refactor!: address ToDos

- README.md
- projects/material-css-vars/src/lib/material-css-vars.module.ts
- src/app/app.config.ts
- src/main.ts
Adds a `provideMaterialCssVars` method to setup the library in standalone workspaces.
Closes #159
> feat: offer standalone friendly API

- projects/material-css-vars/src/lib/_mat-lib-overwrites.scss
Fixes the contrast color of Mini FABs
Closes #163
> fix: respect contrast color of mini FABs

- projects/material-css-vars/src/lib/material-css-vars.module.ts
Refactors the `MaterialCssVarsModule` providers to use the `provideMaterialCssVars()` function internally, to simplify the setup.
n/a
> refactor: simplify provider setup

- projects/material-css-vars/package.json
- projects/material-css-vars/src/lib/legacy/main.scss
- projects/material-css-vars/src/lib/legacy/public-color-util.scss
- projects/material-css-vars/src/lib/legacy/public-util.scss
- projects/material-css-vars/src/lib/legacy/variables.scss
Removes the legacy SCSS entrypoints (including `src/lib/`) which are deprecated and throwing warnings for a long time already.
List any existing issues this PR resolves
> fix!: remove legacy SCSS entrypoints

- projects/material-css-vars/src/lib/_mat-lib-overwrites.scss
- src/app/app.component.html
Angular Material v19 added support for overriding the styles of their components with [overrides SCSS mixins](https://material.angular.io/guide/theming#component-tokens). This PR refactors the existing style overrides to use that mixins, wherever possible.
n/a
> Reduce targeting of internal Angular Material elements
